### ISSUE TITLE
`git` plugin no longer public 

### ISSUE THREAD

**Issue by ganawaj** [coredns/coredns.io#303]
Probably not the best place to ask, but noticed that the `git` plugin that's listed under external plugins no longer exists. 

I've been using the plugin on and off for a while - do we know it's status?

**Comment by e-minguez** [comment]
The repo is gone, let me summon the creator @miekg . Thanks!

**Comment by miekg** [comment]
had to look, but I think I axed it last year in a massive spring cleaning. Didn't have the
forsight to archive it... so it's gone.

It was however a trivial conversion of the old caddy git plugin, so that might be a good
starting point if you need this. Or maybe some copy still roams the interwebs?

[ Quoting ***@***.***> in "Re: [coredns/coredns.io] `git` plug..." ]
>The repo is gone, let me summon the creator @miekg . Thanks!
>
>—
>Reply to this email directly, view it on GitHub, or unsubscribe.
>You are receiving this because you were mentioned.*Message ID: <coredns/coredns
>.***@***.***>
>
/Miek

--
Miek Gieben

**Comment by ganawaj** [comment]
Alright good to know, I think I'll give a shot at reviving it, thank you @miekg!

**Comment by e-minguez** [comment]
> Alright good to know, I think I'll give a shot at reviving it, thank you @miekg!

If you have a local copy maybe you can just create a repo and send a PR here to point to the new URL

**Comment by SuperQ** [comment]
It looks like there are a few forks laying around:
* https://github.com/Xervon/coredns-git
* https://github.com/ekmixon/coredns-git
* https://github.com/tictak/coredns-git

**Comment by miekg** [comment]
Gotta love git
